name = "UTCDateTimes"
uuid = "0f7cfa37-7abf-4834-b969-a8aa512401c2"
authors = ["Invenia Technical Computing Corporation"]
version = "1.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
TimeZones = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
